### ISSUE TITLE
[1.5.3 - WorldGuard Flag Bug] - softcrash when using the plugin without worldguard being present.

### ISSUE THREAD

**Issue by Terminal-Access** [DevCyntrix/death-chest#14]
**Update:** Please see the comment below as to why I beleive this is happening and a suggested fix for the issue.

Death Chest: v1.5.3
Server: PaperMC 1.19.23 Build 232 (any build that supports running this plugin)

There appaears to be a softcrash happening upon server start up when using this plugin with out the preseance of the worldguard plugin. 

```
[16:29:11] [Server thread/INFO]: [DeathChest] Loading DeathChest v1.5.3
[16:29:11] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_19_R1.CraftServer] com/sk89q/worldguard/protection/flags/Flag initializing DeathChest v1.5.3 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldguard/protection/flags/Flag
	at de.helixdevs.deathchest.DeathChestPlugin.onLoad(DeathChestPlugin.java:80) ~[death-chest-1.5.3-all.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:429) ~[paper-1.19.2.jar:git-Paper-235]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:278) ~[paper-1.19.2.jar:git-Paper-235]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-235]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-235]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.protection.flags.Flag
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:177) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:124) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 6 more
```

Marked as a softcrash as the plugin appears to finish loading later on in the server startup process.

**Comment by Terminal-Access** [comment]
Looks like the check that you are performing happens within the class "WorldGuardDeathChestFlag.java" Unofrtunatly for that class to load it first relies upon two imports from worldedit it';s self and i believe that's what is causing the softcrash, it's in effect negating the check you are trying to perform within that class.

If i may offer a simple solution,  it would be to refactor the code soi that you move the worldguard check the main plugin class's on load section, perform the check here and then if worldguard is detected goa head and call for the supported class to be registered.


e.g something a kin to the following:

**DeathChestPlugin.java**
>     @Override
>     public void onLoad() 
>     {
>         PluginManager pluginManager = Bukkit.getPluginManager();
>         Plugin plugin = pluginManager.getPlugin("WorldGuard");
>         if (plugin != null) 
>         { 
>             WorldGuardDeathChestFlag.register(); 
>         }
>     }

and then adjust the remaining code in WorldGuardDeathChestFlag.java" to do it's thing.

Hope this helps

Kind regards
Lee

p.s: loving the plugin, awesome work thus far! ~ much love and appreciation!!

**Comment by DevCyntrix** [comment]
Hi, thank you very much for your efforts! If I am at home I can implement this fix but if you want you can create an Pull Request and test your fix by yourself. Then we could fix the bug faster and you have contributed to this plugin :).

Best regards
Ricardo
