### ISSUE TITLE
Higher than usual resource drain?

### ISSUE THREAD

**Issue by AndrewChqng** [DevCyntrix/death-chest#23]
[https://spark.lucko.me/p86MimpATf](url)
Hi, terribly sorry but just thought I'd check as in the plugins section of the Spark report it suggests Death-Chest is using almost 14%? The server was idling the whole time so not too sure but it seems extremely high compared to the other plugins. If it's intended it's absolutely fine but thought I'd check just in case.

**Comment by AndrewChqng** [comment]
Not sure if this is relevant but get constant errors of this sometimes if chunks with death-chests are loaded
```
[18:48:11 WARN]: [DeathChest] Plugin DeathChest v1.5.8 generated an exception while executing task 1418467
java.lang.IllegalStateException: async operation is not supported
        at me.filoghost.holographicdisplays.plugin.lib.fcommons.Preconditions.checkState(Preconditions.java:69) ~[HolographicDisplays-3.0.1-SNAPSHOT.jar:?]
        at me.filoghost.holographicdisplays.plugin.lib.fcommons.Preconditions.checkMainThread(Preconditions.java:92) ~[HolographicDisplays-3.0.1-SNAPSHOT.jar:?]
        at me.filoghost.holographicdisplays.core.CorePreconditions.checkMainThread(CorePreconditions.java:13) ~[HolographicDisplays-3.0.1-SNAPSHOT.jar:?]
        at me.filoghost.holographicdisplays.core.base.BaseTextHologramLine.setText(BaseTextHologramLine.java:35) ~[HolographicDisplays-3.0.1-SNAPSHOT.jar:?]
        at de.helixdevs.deathchest.support.hologram.holographicdisplays.HDTextLine.rename(HDTextLine.java:17) ~[death-chest-1.5.8-all.jar:?]
        at de.helixdevs.deathchest.DeathChestImpl$1.lambda$run$0(DeathChestImpl.java:165) ~[death-chest-1.5.8-all.jar:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
        at de.helixdevs.deathchest.DeathChestImpl$1.run(DeathChestImpl.java:160) ~[death-chest-1.5.8-all.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1845]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.2.jar:git-Purpur-1845]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
```

**Comment by DevCyntrix** [comment]
Thank you very much I will fix it!

**Comment by DevCyntrix** [comment]
Would you like to add my on discord that we can test the fix for the first issue?

Best regards
Ricardo

**Comment by DevCyntrix** [comment]
These bugs should be fixed now. Thank you very much for your efforts!
